### ISSUE TITLE
Doesn't work when using USER

### ISSUE THREAD

**Issue by rubenv** [janeczku/docker-alpine-kubernetes#7]
We have a Docker container that runs with reduced privileges:

```
USER pgbouncer
```

This container used to run with alpine:3.3, when switching to alpine-kubernetes, things fail:

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

What should we do about this?

**Comment by janeczku** [comment]
Hi, i am afraid the `USER` instruction is not supported because the built-in process supervisor requires root privileges during container initialization (see https://github.com/just-containers/s6-overlay#notes).

Instead of using `USER`, you could drop privileges in the `CMD` instruction:

`CMD ["su", "pgbouncer", "-s", "/bin/sh", "-c", "/usr/sbin/somebinary"]`

Hope that helps!

**Comment by rubenv** [comment]
That works! I'm now seeing a different problem (my Go binary gets `[::1]`, whereas a command-line dig gets te correct `10.3.0.137`), but that looks like a separate issue.

Thanks!

**Comment by janeczku** [comment]
Awesome! :tada: 

> (my Go binary gets [::1], whereas a command-line dig gets te correct 10.3.0.137

The reason you see different results is because the go binary by default queries both IPv6 and IPv4 addresses when resolving hostnames. What DNS servers do your containers use?

**Comment by rubenv** [comment]
Found the cause, it was my own stupidity! Works like a charm now!

Thanks again!
